version: '3'
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
  springbootapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
